# Generated by Django 5.1.6 on 2026-08-04 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments', '0001_initial'),
        ('tasks', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks.task', verbose_name='task'),
        ),
        migrations.AddField(
            model_name='comment',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='workspaces.workspace', verbose_name='workspace'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['document', 'created_at'], name='comment_document_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['task', 'created_at'], name='comment_task_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent'], name='comment_parent_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['workspace', '-created_at'], name='comment_ws_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('document__isnull', False), ('task__isnull', True)), models.Q(('document__isnull', True), ('task__isnull', False)), _connector='OR'), name='comment_targets_exactly_one_resource'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(condition=models.Q(('parent__isnull', True), ('is_resolved', False), _connector='OR'), name='comment_reply_cannot_be_resolved'),
        ),
    ]
