# Generated by Django 5.1.6 on 2026-08-03 14:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField(verbose_name='version number')),
                ('content', models.TextField(blank=True, default='', verbose_name='content')),
                ('summary', models.CharField(blank=True, default='', help_text='One line describing the change, e.g. "Added Apple Pay section".', max_length=200, verbose_name='summary')),
            ],
            options={
                'verbose_name': 'document version',
                'verbose_name_plural': 'document versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('content', models.TextField(blank=True, default='', verbose_name='content')),
                ('excerpt', models.CharField(blank=True, default='', max_length=200, verbose_name='excerpt')),
                ('revision', models.PositiveIntegerField(default=1, verbose_name='revision')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_documents', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
                'ordering': ['-updated_at', 'id'],
            },
        ),
    ]
