import { Lock } from 'lucide-react'

import { isMockEngine } from '@/types/ai'
import { formatAbsoluteTime, formatRelativeTime } from '@/utils/format'
import { cn } from '@/utils/cn'

/**
 * Where a result came from. (CLAUDE.md §47, §50)
 *
 * Every generated artefact in this panel carries one of these. The engine is
 * whatever actually answered: a model id when Django reached a provider, or
 * `mock-heuristic` when it fell back to the rule-based reader that reads the
 * document and answers with rules. The label says which rather than letting the
 * sparkle icon imply otherwise.
 *
 * This is not decoration. A user deciding whether to trust a summary needs to
 * know what produced it, and an interface that hides the difference between a
 * model and a regular expression has made that decision for them.
 */

export interface AIProvenanceProps {
  engine: string
  generatedAt: string
  className?: string
}

export function AIProvenance({ engine, generatedAt, className }: AIProvenanceProps) {
  return (
    <p className={cn('text-caption text-foreground-subtle', className)}>
      {isMockEngine(engine)
        ? 'Mocked — extracted from this document by rule, not by a model.'
        : `Generated by ${engine}.`}{' '}
      <time dateTime={generatedAt} title={formatAbsoluteTime(generatedAt)}>
        {formatRelativeTime(generatedAt)}
      </time>
    </p>
  )
}

/**
 * The panel's standing footnote.
 *
 * States the architecture rather than a reassurance: requests go to Django, and
 * no provider key exists in this package because everything shipped to the
 * browser is readable by whoever is holding it. (§9, §50, §66)
 */
export function AISecurityNote({ className }: { className?: string }) {
  return (
    <p
      className={cn(
        'flex items-start gap-1.5 text-caption text-foreground-subtle',
        className,
      )}
    >
      <Lock aria-hidden="true" className="mt-px size-3 shrink-0" />
      <span>Requests go through Django. No AI key is shipped to the browser.</span>
    </p>
  )
}
