# Generated by Django 5.1.6 on 2026-08-03 06:43

import apps.accounts.managers
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(help_text='Used to sign in. Case-insensitively unique.', max_length=254, unique=True, verbose_name='email address')),
                ('name', models.CharField(help_text='Display name shown to collaborators.', max_length=150, verbose_name='full name')),
                ('avatar_url', models.URLField(blank=True, default='', help_text='Empty renders initials on the client.', max_length=500, verbose_name='avatar URL')),
                ('title', models.CharField(blank=True, default='', help_text='Role within the team, e.g. "Frontend Engineer".', max_length=100, verbose_name='job title')),
                ('is_active', models.BooleanField(default=True, help_text='Deactivate instead of deleting to preserve authored content.', verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, help_text='Grants access to the Django admin. Unrelated to workspace roles.', verbose_name='staff status')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['name', 'email'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='user_email_ci_unique')],
            },
            managers=[
                ('objects', apps.accounts.managers.UserManager()),
            ],
        ),
    ]
