# Generated by Django 5.1.6 on 2026-08-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, default=None, help_text='Set automatically the first time this person signs in with Google.', max_length=255, null=True, unique=True, verbose_name='Google account ID'),
        ),
    ]
