# Generated by Django 5.1.6 on 2026-08-03 14:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('slug', models.SlugField(help_text='URL-safe identifier, unique within the workspace.', max_length=140, verbose_name='slug')),
                ('description', models.TextField(blank=True, default='', max_length=2000, verbose_name='description')),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('on_hold', 'On hold'), ('completed', 'Completed'), ('archived', 'Archived')], default='planning', max_length=12, verbose_name='status')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='due date')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_projects', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='workspaces.workspace', verbose_name='workspace')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'ordering': ['-updated_at', 'id'],
                'indexes': [models.Index(fields=['workspace', '-updated_at'], name='project_ws_updated_idx'), models.Index(fields=['workspace', 'status'], name='project_ws_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'slug'), name='project_workspace_slug_unique')],
            },
        ),
    ]
