# Generated by Django 5.1.6 on 2026-08-04 02:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('project_created', 'Project created'), ('document_created', 'Document created'), ('document_edited', 'Document edited'), ('task_created', 'Task created'), ('task_completed', 'Task completed'), ('member_invited', 'Member invited'), ('comment_added', 'Comment added'), ('ai_action', 'AI action')], max_length=32, verbose_name='action')),
                ('entity_type', models.CharField(choices=[('project', 'Project'), ('document', 'Document'), ('task', 'Task'), ('member', 'Member'), ('comment', 'Comment')], max_length=16, verbose_name='entity type')),
                ('entity_id', models.UUIDField(verbose_name='entity id')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='actor')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='workspaces.workspace', verbose_name='workspace')),
            ],
            options={
                'verbose_name': 'activity',
                'verbose_name_plural': 'activities',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['workspace', '-created_at'], name='activity_ws_created_idx'), models.Index(fields=['entity_type', 'entity_id'], name='activity_entity_idx')],
            },
        ),
    ]
