# Generated by Django 5.1.6 on 2026-08-04 07:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('mention', 'Mention'), ('task_assigned', 'Task assigned'), ('task_completed', 'Task completed'), ('document_shared', 'Document shared'), ('project_update', 'Project update'), ('workspace_invitation', 'Workspace invitation')], max_length=24, verbose_name='type')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('message', models.TextField(blank=True, default='', max_length=1000, verbose_name='message')),
                ('entity_type', models.CharField(choices=[('project', 'Project'), ('document', 'Document'), ('task', 'Task'), ('comment', 'Comment'), ('workspace', 'Workspace')], max_length=16, verbose_name='entity type')),
                ('entity_id', models.UUIDField(verbose_name='entity id')),
                ('href', models.CharField(blank=True, default='', max_length=500, verbose_name='href')),
                ('is_read', models.BooleanField(default=False, verbose_name='read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='read at')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='actor')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='recipient')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='workspaces.workspace', verbose_name='workspace')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notification_user_idx'), models.Index(condition=models.Q(('is_read', False)), fields=['recipient'], name='notification_unread_idx'), models.Index(fields=['workspace', '-created_at'], name='notification_ws_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_read', False)), fields=('recipient', 'type', 'entity_type', 'entity_id'), name='notification_unread_unique_per_entity')],
            },
        ),
    ]
